import { z } from 'zod';
import { Status } from '@prisma/client';

// Use Zod schemas generated by prisma-zod-generator
const StageIdsSchema = z.object({
  prepare: z.string().uuid(),
  codeQuality: z.string().uuid(),
  unitTest: z.string().uuid(),
  build: z.string().uuid(),
  integrationTest: z.string().uuid().optional(),
  deployStaging: z.string().uuid().optional(),
  deployProduction: z.string().uuid(),
});

type StageIds = z.infer<typeof StageIdsSchema>;

const StatusSchema = z.enum([
  Status.SUCCESS,
  Status.FAILURE,
  Status.IN_PROGRESS,
  Status.IDLE,
]);

const StageSchema = z.object({
  id: z.string().uuid(),
  status: StatusSchema,
});

type Stage = z.infer<typeof StageSchema>;

const RunStatusSchema = z.object({
  run: StageSchema,
  stages: z.object({
    prepare: StageSchema,
    codeQuality: StageSchema,
    unitTest: StageSchema,
    build: StageSchema,
    integrationTest: StageSchema.optional(),
    deployStaging: StageSchema.optional(),
    deployProduction: StageSchema,
  }),
});

type RunStatus = z.infer<typeof RunStatusSchema>;

const ContainerVariablesSchema = z.object({
  awsRegion: z.string(),
  awsAccountId: z.string(),
  awsAccessKey: z.string(),
  awsSecretAccessKey: z.string(),
  githubPat: z.string(),
  githubRepoUrl: z.string(),
  codeQualityCommand: z.string().optional(),
  unitTestCommand: z.string().optional(),
  dockerfilePath: z.string(),
  awsEcsCluster: z.string(),
  awsEcsService: z.string(),
  awsEcrRepo: z.string(),
  logSubscriberUrl: z.string().optional(),
});

type ContainerVariables = z.infer<typeof ContainerVariablesSchema>;

// Schema for validating the input data required for the Step Function to run
const SfnInputSchema = z.object({
  awsStepFunction: z.string(),
  serviceId: z.string().uuid(),
  runId: z.string().uuid(),
  stageIds: StageIdsSchema,
  runStatus: RunStatusSchema,
  runFull: z.boolean(),
  autoDeploy: z.boolean(),
  containerVariables: ContainerVariablesSchema,
});

type SfnInput = z.infer<typeof SfnInputSchema>;

export {
  SfnInputSchema,
  SfnInput,
  StageIds,
  Stage,
  RunStatus,
  ContainerVariables,
};
