-- CreateEnum
CREATE TYPE "StageType" AS ENUM ('PREPARE', 'CODE_QUALITY', 'UNIT_TEST', 'INTEGRATION_TEST', 'BUILD', 'DEPLOY_STAGING', 'DEPLOY_PROD');

-- AlterTable
ALTER TABLE "Stage" ADD COLUMN     "type" "StageType" NOT NULL DEFAULT 'PREPARE';
